### ISSUE TITLE
Must have compile time limit

### ISSUE THREAD

**Issue by cuklev** [Alaxe/judgeSystem#2]
Submitting this code:

``` cpp
template<int x, int y>
struct baba{
    baba<x - 1, y> A;
    baba<x, y - 1> B;
};

template<int x>
struct baba<x, 0> {};

template<int x>
struct baba<0, x> {};

int main()
{
    baba<400, 400> todorka;
}
```

clogs the submission queue.

**Comment by Alaxe** [comment]
Fixed with commit d41b884ffe02de0dae4d31c2fa866b5ae18cb0b1.

**Comment by StanislavNikolov** [comment]
I think bumping the timeout is actually a good idea, as this lets competitors use a wider range of solutions, like use c++11's new constexpr and more. 3 seconds is way to low even for "normal" task when running on weaker systems (like raspberries or potatoes).

**Comment by Alaxe** [comment]
While 3 seconds is enough for compilation on the machine the [main build](https://judgesystem.tk) is running, you're right that on weaker systems it may be low. I've moved the timeout to a variable `settings.JUDGE_COMPILE_TL`, so it can be changed, depending on the situation. 

The commit: 55392beff9f8fd003c2579e8c3d6c3f92f3d4774
