### ISSUE TITLE
Multiple "create user" requests shutdown the system

### ISSUE THREAD

**Issue by StanislavNikolov** [Alaxe/judgeSystem#3]
A simple script sending post requests to create new unique users (with invalid emails, but different names/emails), slows down the system. After a few seconds it starts to respond with error "Server Error 500" and then completely shuts down (after 10 seconds).

EDIT:
It looks like a just over a few requests a second make the register form unusable.

**Comment by Alaxe** [comment]
I've added reCAPTCHA to the register form, which should make spamming the register form harder. Sending an email through Gmail takes a bit of time though (a second or two), so it should be done asynchronously with the HTTP request (with a celery task most likely). Once this is implemented, it shouldn't create any errors if the server is under a reasonable load. Hence Gmail is the bottleneck, a custom mail server will be needed to scale the project, but it should be fine for now (testing solutions is an even bigger bottleneck).

**Comment by StanislavNikolov** [comment]
Fixed with 7d90ddedc03b7d1bef4076e1a363fc602d42fdbb
