### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by kenzhegaliyevn** [Alaxe/judgeSystem#5]
I could not to run this project. Can anybody help?

**Comment by Alaxe** [comment]
The instalation and running of JudgeSystem aren't as easy as I would like them to be but, if you are adventurous, there are instructions in README.md. It has never really been meant to be used by other people, and so there's a lack of configuration options. I also don't have the time to do bugfixes, implement new features, etc. If you want a simpler and more mature system, I would recommend checking out [cms](https://github.com/cms-dev/cms).

**Comment by kenzhegaliyevn** [comment]
Alexander, can we talk via skype? I need your help

2017-04-30 19:55 GMT+06:00 Alexander Crustev <notifications@github.com>:

**Comment by Alaxe** [comment]
I am sorry but, as I said in my previous comment, I am neither developing nor supporting this project any more. I strongly recommend looking into [cms](https://github.com/cms-dev/cms) as an alternative.
